version: '3'
services:
  seq:
    image: datalust/seq
    ports: 
      - 80:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FHdmLztMlDXCUbIsVuEn3vjkqJdlJbWsJFMQRUq3G39bnr5xaQ==
    volumes:
      - "./.docker/seq/data:/data"
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - "./.docker/redis/data:/data"
  postgres:
    image: postgres:12
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqserver
    hostname: 'rabbit-mq-host'
#    volumes:
#      - "./.docker/rabbitmq/etc/:/etc/rabbitmq/"
#      - "./.docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia"
#      - "./.docker/rabbitmq/logs/:/var/log/rabbitmq/"
    ports:
      - 5672:5672
      - 15672:15672
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=tSlY4ETLAZ
    volumes:
      - sqlserver:/var/opt/mssql/data
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
#  userservice:
#    container_name: user_service
#    build: 
#      context: ./
#      dockerfile: UserService/Dockerfile
#    depends_on:
#      - sqlserver
#      - rabbitmqserver
#    ports:
#      - "5100:5100"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Production
volumes:
  mongodb:
    driver: local
  sqlserver:
    driver: local