<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.1" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.1" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0-preview.4.21253.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Messages\Commands\Projects\Handlers" />
      <Folder Include="Messages\Events\Projects" />
      <Folder Include="Messages\Queries\Projects\Handlers" />
      <Folder Include="Messages\Queries\Todos\Handlers" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Invoicer.Common\src\Invoicer.Common.csproj" />
    </ItemGroup>

</Project>
