<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Models\" />
    <Folder Include="Repositories\" />
    <Folder Include="Commands\" />
    <Folder Include="Mappers\" />
    <Folder Include="Commands\Handlers\" />
    <Folder Include="Queries\" />
    <Folder Include="Queries\Handlers\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.2" />
    <PackageReference Include="Polly" Version="7.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="InvoiceCommonLib" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Migrations\20200223104349_InitialCreate.Designer.cs" />
    <Compile Remove="Migrations\UserDBContextModelSnapshot.cs" />
    <Compile Remove="Migrations\20200223104349_InitialCreate.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\APIGateway\APIGateway.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>
</Project>
