// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectsService.Repositories;

namespace ProjectsService.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20210905050433_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ProjectsService.DTO.ProjectDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ProjectsService.DTO.TodoDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectDtoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDtoId");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("ProjectsService.DTO.TodoTagDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("TodoDtoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TodoDtoId");

                    b.ToTable("TodoTag");
                });

            modelBuilder.Entity("ProjectsService.DTO.TodoDto", b =>
                {
                    b.HasOne("ProjectsService.DTO.ProjectDto", null)
                        .WithMany("Todos")
                        .HasForeignKey("ProjectDtoId");
                });

            modelBuilder.Entity("ProjectsService.DTO.TodoTagDto", b =>
                {
                    b.HasOne("ProjectsService.DTO.TodoDto", null)
                        .WithMany("Tags")
                        .HasForeignKey("TodoDtoId");
                });

            modelBuilder.Entity("ProjectsService.DTO.ProjectDto", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("ProjectsService.DTO.TodoDto", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
