version: '3'
services:
  seq:
    image: datalust/seq
    volumes:
      - "./.docker/seq/data:/data"
    ports: 
      - 80:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FPatFoASWnx+Y6LVpnNu9ck4Q2Gud1T7ZFW3mrSy4OGIMAiiXg==
  postgres:
    image: postgres:12
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  adminer:
    image: adminer
    hostname: adminer
    ports:
      - 8081:8080
  rabbitmqserver:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqserver
    hostname: 'rabbit-mq-host'
    volumes:
      - "./.docker/rabbitmq/etc/:/etc/rabbitmq/"
      - "./.docker/rabbitmq/data/:/var/lib/rabbitmq/"
      - "./.docker/rabbitmq/logs/:/var/log/rabbitmq/"
    ports:
      - 5672:5672
      - 15672:15672
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    ports:
      - 1434:1433
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=tSlY4ETLAZ
    volumes:
      - sqlserver:/var/opt/mssql/data
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
#  userservice:
#    container_name: user_service
#    build: 
#      context: ./
#      dockerfile: UserService/Dockerfile
#    depends_on:
#      - sqlserver
#      - rabbitmqserver
#    ports:
#      - "5100:5100"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Production
volumes:
  mongodb:
    driver: local
  sqlserver:
    driver: local