version: '3'
services:
  rabbitmqserver:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqserver
    hostname: 'rabbit-mq-host'
    volumes:
      - "./.docker/rabbitmq/etc/:/etc/rabbitmq/"
      - "./.docker/rabbitmq/data/:/var/lib/rabbitmq/"
      - "./.docker/rabbitmq/logs/:/var/log/rabbitmq/"
    ports:
      - 5672:5672
      - 15672:15672
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=tSlY4ETLAZ
  userservice:
    container_name: user_service
    build: 
      context: ./
      dockerfile: UserService/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmqserver
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production