<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PackageId>InvoiceCommonLib</PackageId>
    <Version>1.0.0-alpha</Version>
    <Authors>Ryan Reichenberg</Authors>
    <PackageDescription>This package adds common methods and interfaces for the Invoicer app!</PackageDescription>
    <RepositoryUrl>https://github.com/RyannnnnnR/Invoicer.Common</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Convey" Version="0.5.518" />
    <PackageReference Include="Convey.Auth" Version="0.5.518" />
    <PackageReference Include="Convey.CQRS.Commands" Version="0.5.518" />
    <PackageReference Include="Convey.CQRS.Events" Version="0.5.518" />
    <PackageReference Include="Convey.CQRS.Queries" Version="0.5.518" />
    <PackageReference Include="Convey.Logging" Version="0.5.518" />
    <PackageReference Include="Convey.MessageBrokers" Version="0.5.518" />
    <PackageReference Include="Convey.MessageBrokers.CQRS" Version="0.5.518" />
    <PackageReference Include="Convey.Persistence.MongoDB" Version="0.5.518" />
    <PackageReference Include="Convey.Persistence.Redis" Version="0.5.518" />
    <PackageReference Include="Convey.Secrets.Vault" Version="0.5.518" />
    <PackageReference Include="Convey.Security" Version="0.5.518" />
    <PackageReference Include="Convey.Tracing.Jaeger" Version="0.5.518" />
    <PackageReference Include="Convey.Tracing.Jaeger.RabbitMQ" Version="0.5.518" />
    <PackageReference Include="EntityFramework" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SmartFormat.NET" Version="2.5.3" />
  </ItemGroup>
</Project>
