// <auto-generated />
using System;
using InvoicingService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InvoicingService.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20220415110607_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("InvoicingService.DTO.InvoiceDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<bool>("Recurring")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<double>("TaxRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("InvoicingService.DTO.InvoiceDto", b =>
                {
                    b.OwnsMany("InvoicingService.DTO.LineItemDto", "Items", b1 =>
                        {
                            b1.Property<Guid>("InvoiceDtoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<decimal?>("Price")
                                .HasColumnType("numeric");

                            b1.Property<int?>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("InvoiceDtoId", "Id");

                            b1.ToTable("LineItemDto");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceDtoId");
                        });

                    b.OwnsOne("InvoicingService.Domain.Contact", "BillFrom", b1 =>
                        {
                            b1.Property<Guid>("InvoiceDtoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BusinessName")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("EmailAddress")
                                .HasColumnType("text");

                            b1.Property<string>("MobileNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("StreetAddress")
                                .HasColumnType("text");

                            b1.HasKey("InvoiceDtoId");

                            b1.ToTable("Invoice");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceDtoId");
                        });

                    b.OwnsOne("InvoicingService.Domain.Contact", "BillTo", b1 =>
                        {
                            b1.Property<Guid>("InvoiceDtoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BusinessName")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("EmailAddress")
                                .HasColumnType("text");

                            b1.Property<string>("MobileNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("StreetAddress")
                                .HasColumnType("text");

                            b1.HasKey("InvoiceDtoId");

                            b1.ToTable("Invoice");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceDtoId");
                        });

                    b.Navigation("BillFrom");

                    b.Navigation("BillTo");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
