<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
     <PackageId>InvoiceCommonLib</PackageId>
    <Version>1.0.0</Version>
    <Authors>Ryan Reichenberg</Authors>
    <PackageDescription>Common classes and utilities used for Invoicer services</PackageDescription>
    <RepositoryUrl>https://github.com/RyannnnnnR/invoicer-backend-microservices/</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="5.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
  </ItemGroup>
</Project>