name: Invoicer.Common package and publish
on:
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: Build and pubslih
    # This job runs on Linux
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/RyannnnnnR/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build src/Invoicer.Common
      - name: Create the package
        run: dotnet pack --configuration Release Invoicer.Common
      - name: Publish the package to GPR
        run: dotnet nuget push src/Invoicer.Common/bin/Release/*.nupkg
